import { render, screen } from '@testing-library/react'
import React from 'react'
import { describe, expect, it, vi } from 'vitest'

const mockPush = vi.fn()

class MockIntersectionObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
}

vi.stubGlobal('IntersectionObserver', MockIntersectionObserver)

vi.mock('next/navigation', () => ({
  useRouter: () => ({
    push: mockPush,
    replace: vi.fn(),
    prefetch: vi.fn(),
    back: vi.fn(),
    forward: vi.fn(),
    refresh: vi.fn(),
  }),
  usePathname: () => '/',
}))

vi.mock('@/nexus/api', () => ({
  authApi: {
    me: vi.fn().mockResolvedValue({ ok: true, data: { user: null } }),
    login: vi.fn(),
    signup: vi.fn(),
    logout: vi.fn(),
  },
  postsApi: {
    list: vi.fn().mockResolvedValue({ ok: true, data: { docs: [] } }),
  },
  toNexusBlog: (blog: unknown) => blog,
}))

import { NexusProvider } from '@/nexus/NexusProvider'

import HomePage from '../../src/app/(nexus)/page'

describe('home page', () => {
  it('renders the Nexus homepage content on the root URL', async () => {
    render(React.createElement(NexusProvider, null, React.createElement(HomePage)))

    expect(await screen.findByText('Generated by Nexus Writer')).toBeTruthy()
  })
})
